"""SigV4 signing, checked against vectors AWS's own implementation produced.

This is the one place in the project where a fixture is NOT something the test
author invented: `tests/fixtures/sigv4_vectors.json` was generated by botocore's
`S3SigV4Auth` in a throwaway venv and vendored. botocore never becomes a project
dependency (see the zero-dependency rule), but it is the reference for whether
the signature is right, and a signature that is subtly wrong produces a 403
rather than visibly wrong data.

AWS's current documentation gives the algorithm but replaces every worked
example's signature with a `{{calculated-signature}}` placeholder, so there is
no published hex vector to use instead.

Regenerate with the scratchpad `gen_vectors.py`; the timestamp is read back from
the signed request because S3SigV4Auth sets X-Amz-Date itself.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlsplit

import pytest

from autosiem.sigv4 import (
    EMPTY_PAYLOAD_SHA256,
    canonical_headers,
    canonical_query_string,
    canonical_request,
    credential_scope,
    sign_request,
    signing_key,
    string_to_sign,
    uri_encode,
)

VECTORS = json.loads((Path(__file__).parent / "fixtures" / "sigv4_vectors.json").read_text())


def _sign_case(case: dict) -> str:
    parts = urlsplit(case["url"])
    when = datetime.strptime(case["amz_date"], "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc)
    return sign_request(
        method=case["method"], host=parts.netloc, path=unquote(parts.path) or "/",
        query=dict(parse_qsl(parts.query, keep_blank_values=True)),
        region=case["region"], service=case["service"],
        access_key=VECTORS["access_key"], secret_key=VECTORS["secret_key"],
        session_token=case["session_token"], now=when,
    )["Authorization"]


@pytest.mark.parametrize("case", VECTORS["cases"], ids=lambda c: c["label"])
def test_signature_matches_the_aws_reference_implementation(case: dict) -> None:
    assert _sign_case(case) == case["authorization"]


def test_the_fixture_actually_covers_the_hard_cases() -> None:
    """Guard the guard: a trimmed fixture would silently weaken every test above."""
    labels = {case["label"] for case in VECTORS["cases"]}
    assert {
        "s3_get_object_nested_key",          # '/' must stay literal in a key
        "s3_key_with_spaces_and_plus",       # %20 not '+', and '+' encoded
        "s3_continuation_token_needs_encoding",  # query value with / + =
        "s3_with_session_token",             # token is inside the signature
        "s3_root_no_query",                  # empty canonical query string
    } <= labels
    assert len(VECTORS["cases"]) >= 6


# -- the encoding rules the canonical request depends on -------------------

def test_uri_encode_leaves_only_the_unreserved_set() -> None:
    assert uri_encode("AZaz09-_.~", is_path=False) == "AZaz09-_.~"


def test_uri_encode_uses_uppercase_hex_and_percent_twenty_for_space() -> None:
    """AWS requires uppercase hex; a space is %20, never '+'."""
    assert uri_encode("a b", is_path=False) == "a%20b"
    assert uri_encode("a+b", is_path=False) == "a%2Bb"
    assert uri_encode("\x1a", is_path=False) == "%1A"


def test_slash_is_literal_in_a_path_and_encoded_in_a_query() -> None:
    assert uri_encode("AWSLogs/123/CloudTrail", is_path=True) == "AWSLogs/123/CloudTrail"
    assert uri_encode("AWSLogs/123", is_path=False) == "AWSLogs%2F123"


def test_query_string_sorts_after_encoding() -> None:
    """The signature is over the encoded form, so a pre-encoding sort can differ."""
    assert canonical_query_string({"b": "2", "a": "1"}) == "a=1&b=2"
    assert canonical_query_string({"a b": "1", "a+": "2"}) == "a%20b=1&a%2B=2"


def test_a_subresource_keeps_its_empty_value() -> None:
    assert canonical_query_string({"acl": ""}) == "acl="


def test_headers_are_lowercased_sorted_and_trimmed() -> None:
    block, signed = canonical_headers({"X-Amz-Date": " 20260915T120000Z ", "Host": "s3.test"})
    assert block == "host:s3.test\nx-amz-date:20260915T120000Z\n"
    assert signed == "host;x-amz-date"


def test_empty_payload_hash_is_the_documented_constant() -> None:
    assert EMPTY_PAYLOAD_SHA256 == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"


def test_canonical_request_has_the_six_documented_lines() -> None:
    request, signed = canonical_request(
        "GET", "/", {"list-type": "2"},
        {"host": "s3.test", "x-amz-date": "20260915T120000Z"}, EMPTY_PAYLOAD_SHA256)
    lines = request.split("\n")
    assert lines[0] == "GET"
    assert lines[1] == "/"
    assert lines[2] == "list-type=2"
    assert lines[-1] == EMPTY_PAYLOAD_SHA256
    assert lines[-2] == signed == "host;x-amz-date"


def test_credential_scope_and_string_to_sign_shape() -> None:
    scope = credential_scope("20260915", "us-east-1", "s3")
    assert scope == "20260915/us-east-1/s3/aws4_request"
    lines = string_to_sign("20260915T120000Z", scope, "canonical").split("\n")
    assert lines[0] == "AWS4-HMAC-SHA256"
    assert lines[1] == "20260915T120000Z"
    assert lines[2] == scope
    assert len(lines) == 4 and len(lines[3]) == 64


def test_the_signing_key_is_scoped_to_date_region_and_service() -> None:
    """Changing any scope element must change the key, or a leak is unbounded."""
    base = signing_key("secret", "20260915", "us-east-1", "s3")
    assert base != signing_key("secret", "20260916", "us-east-1", "s3")
    assert base != signing_key("secret", "20260915", "eu-west-1", "s3")
    assert base != signing_key("secret", "20260915", "us-east-1", "logs")
    assert base == signing_key("secret", "20260915", "us-east-1", "s3")


# -- the header set the caller must send verbatim ---------------------------

def test_sign_request_returns_every_header_it_signed() -> None:
    headers = sign_request(
        method="GET", host="s3.test", path="/", query={},
        region="us-east-1", service="s3", access_key="AK", secret_key="SK",
        now=datetime(2026, 9, 15, 12, tzinfo=timezone.utc))
    signed = headers["Authorization"].split("SignedHeaders=")[1].split(",")[0]
    for name in signed.split(";"):
        assert name in headers, f"{name} is signed but not returned"
    assert headers["x-amz-content-sha256"] == EMPTY_PAYLOAD_SHA256


def _authorization(*, method: str = "GET", host: str = "s3.test", path: str = "/",
                   query: dict[str, str] | None = None, region: str = "us-east-1",
                   secret_key: str = "SK", session_token: str = "") -> str:
    return sign_request(
        method=method, host=host, path=path, query=query or {}, region=region,
        service="s3", access_key="AK", secret_key=secret_key, session_token=session_token,
        now=datetime(2026, 9, 15, 12, tzinfo=timezone.utc),
    )["Authorization"]


def test_a_session_token_is_signed_not_merely_attached() -> None:
    """A token swapped after signing must invalidate the request."""
    with_token = _authorization(session_token="TOKEN")
    assert "x-amz-security-token" in with_token
    assert with_token != _authorization()


def test_the_signature_changes_with_every_signed_input() -> None:
    base = _authorization()
    assert _authorization(path="/other") != base
    assert _authorization(query={"a": "1"}) != base
    assert _authorization(host="other.test") != base
    assert _authorization(secret_key="OTHER") != base
    assert _authorization(method="HEAD") != base
